### ISSUE TITLE
Kernel Panic while trying to load "pc_speaker.o" module

### ISSUE THREAD

**Issue by TalonTheRaven** [TheUltimateFoxOS/FoxOS#13]
**Describe the bug**
The Horizon Kernel panics while trying to load the "pc_speaker.o" module.

**To Reproduce**
1. Download repo
2. Build and Run FoxOS using the command: `make run-bios USER_CFLAGS="-DDEBUG -DMEMORY_TRACKING -DBOOTINFO -fsanitize=undefined -DUBSAN_SUPRES_TYPE_MISSMATCH"`
3. The Horizon Kernel should panic while booting

**Expected behavior**
The Operating System should be running with no issues.

**Screenshot**
![Screenshot from 2022-05-31 16-04-23](https://user-images.githubusercontent.com/105325988/171284596-440ce78d-330d-4eba-851a-1dc38b63dd05.png)

**System information:**
 - Running Pop!_OS 22.04 on real hardware

**Additional context**
Debug Log File:
[log.txt](https://github.com/TheUltimateFoxOS/FoxOS/files/8809567/log.txt)

**Comment by Glowman554** [comment]
Hi did you use the gcc provided by your system or did you use the toolchain.sh file to build our toolchain? If you didn't build the toolchain then this can be the problem

**Comment by TalonTheRaven** [comment]
Hello, @Glowman554
I was using the toolchain that was built-in with my Linux distro, but I never though to try to build the FoxOS Toolchain. After building the toolchain, I attempted to build FoxOS and it fixed the problem. Thank you for your help!
