### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by ASMHSE** [TheUltimateFoxOS/FoxOS#18]
Following Readme for Ubuntu:

CPP pci/pci.cpp -> ../lib/.//pci/pci.o
pci/pci.cpp: In function ‘void pci::register_pci_driver(uint8_t, uint8_t, uint8_t, void (*)(pci::pci_header_0_t*, uint16_t, uint16_t, uint16_t))’:
pci/pci.cpp:173:2: sorry, unimplemented: non-trivial designated initializers not supported
  };
  ^

**Comment by ASMHSE** [comment]
It's your Makefile:

FOX_GCC_PATH=/usr/local/foxos-x86_64_elf_gcc

**Comment by Glowman554** [comment]
It uses the system compiler of the toolchain isn't installed. Did you run toolchain.sh to install the toolchain?

**Comment by ASMHSE** [comment]
Must be system compiler because no gcc in /usr/local/

**Comment by Glowman554** [comment]
Then try building the toolchain since the system compiler might be too old or something like that

**Comment by ASMHSE** [comment]
That was. Build perfect now. Thanks.
