### ISSUE TITLE
Docker build fails unexpected

### ISSUE THREAD

**Issue by Ezrashaw** [TheUltimateFoxOS/FoxOS#6]
**Describe the bug**
Running the docker image and running `make` works properly however `make img` fails with the error:
`
sh disk.sh /usr/local/foxos-x86_64_elf_gcc
: not found disk.sh: 
dd: invalid number: '93750\r'
: not found disk.sh: 
: not found disk.sh: sh
: not found disk.sh: 
disk.sh: 59: disk.sh: Syntax error: end of file unexpected (expecting "then")
make: *** [Makefile:18: img] Error 2
`

**To Reproduce**
1. Download the repo
2.  Run the supplied docker image.
3. `cd` into the FoxOS directory.
4. Type `make` and wait.
5. Type `make img` and the build fails. 

**Expected behavior**
I would expect that the OS properly build and run.

**System information (please complete the following information):**
- Running in a Debian 11 VM

**Comment by ImDaBigBoss** [comment]
There's a problem with losetup. We will try to find a workaround. Sorry for the inconvenience, we'll keep you up to date.

**Comment by Ezrashaw** [comment]
Cool, thx a lot.

**Comment by Glowman554** [comment]
Hey so we did look into the issue first of all we noticed that you need to run docker using `docker run -it --rm -v /dev:/dev --privileged -v $PWD:/root/FoxOS ghcr.io/theultimatefoxos/foxos-toolchain:latest` and the second issue was we forgot the gdisk package. we did push a fixed image make sure to pull it

**Comment by Ezrashaw** [comment]
Correct me if I'm wrong but don't you also need `qemu-system`?

**Comment by Glowman554** [comment]
That is needed to run the vm but if I'm not wrong you will have problems with the xserver/wailand if you run from docker

**Comment by Ezrashaw** [comment]
The image now seems to build but QEMU is failing?? `gtk initialization failed`?

**Comment by Glowman554** [comment]
That is expected because of docker sandboxing it can't connect to the xserver/wailand. The docker container is only meant to build a image.

**Comment by Ezrashaw** [comment]
ohh, that explains a lot. Everything is working. Thx a lot (hope I didn't bother you too much).
