### ISSUE TITLE
Website small issue

### ISSUE THREAD

**Issue by DonutDev** [TheUltimateFoxOS/FoxOS#7]
Go to https://theultimatefoxos.github.io/
Discord is misspelled. Instead it says Discod
![2021-10-16_09-55](https://user-images.githubusercontent.com/58142952/137577225-7f261881-7230-4b8d-95f6-15fce9fea031.png)

**Comment by ImDaBigBoss** [comment]
Well that’s a bit stupid. Thank you for pointing it out!
