### ISSUE TITLE
Minor spelling issues on the website

### ISSUE THREAD

**Issue by DonutDev** [TheUltimateFoxOS/FoxOS#8]
**Describe the bug**
"Performance" is spelled as "performence" on the website

**To Reproduce**
1. Go to https://theultimatefoxos.dev/ 
2. Read the first sentence

**Expected behavior**
Expected that Performance would be wrote correctly

**Additional context**
TLDR: Performance isn't correctly spelled in the first sentence
![image](https://user-images.githubusercontent.com/58142952/148992330-30f8b0fa-1779-49ce-81e6-ff3828e219de.png)

**Comment by Glowman554** [comment]
Thanks for the report it should be fixed now.
